output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false

pep8:
  full: true
  options:
    max-line-length: 120
  disable:
    - E731

pep257:
  disable:
    - D203
    - D212

pylint:
  options:
    max-line-length: 120