output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: true

pep8:
  full: true
  options:
    max-line-length: 120

pep257:
  disable:
    - D203
    - D212

pylint:
  options:
    max-line-length: 120