version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - export LOG_LEVEL=CRITICAL
      - export OUR_COMMIT_SHA=`git rev-parse HEAD`
      - bandit -r -q .
      - prospector
      - coverage run --source='.' -m unittest
      - coverage report -m --fail-under=100 --omit=*/__init__.py,tests/*,setup.py,examples/*
